### ISSUE TITLE
TypeError upon inputting password

### ISSUE THREAD

**Issue by firecurious** [OllieTerrance/SkPy#23]
I consistently get this error when attempting to sign into Skype:

`TypeError: request() got an unexpected keyword argument 'json'`

I'm just using the code from the basic usage page.

```
from skpy import Skype
from getpass import getpass

Skype("[username]", getpass())
```

I upgraded the Requests library to 2.11.1 in both Python 2.7 and Python 3, but I still get this error. I'm using Ubuntu 14.04.

Here's the full traceback in Python 2.7:

```
Traceback (most recent call last):
  File "[path]/run.py", line 4, in <module>
    sk = Skype("[username]", getpass())
  File "build/bdist.linux-i686/egg/skpy/main.py", line 70, in __init__
  File "build/bdist.linux-i686/egg/skpy/conn.py", line 262, in getSkypeToken
  File "build/bdist.linux-i686/egg/skpy/conn.py", line 404, in login
  File "build/bdist.linux-i686/egg/skpy/conn.py", line 521, in getRegToken
  File "build/bdist.linux-i686/egg/skpy/conn.py", line 205, in __call__
TypeError: request() got an unexpected keyword argument 'json'
```

And in Python 3:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/skpy/main.py", line 68, in __init__
    self.conn.readToken()
  File "/usr/local/lib/python3.4/dist-packages/skpy/conn.py", line 294, in readToken
    raise SkypeAuthException("No token file specified")
skpy.conn.SkypeAuthException: No token file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[path]/run.py", line 4, in <module>
    sk = Skype("[username]", getpass())
  File "/usr/local/lib/python3.4/dist-packages/skpy/main.py", line 70, in __init__
    self.conn.getSkypeToken()
  File "/usr/local/lib/python3.4/dist-packages/skpy/conn.py", line 259, in getSkypeToken
    self.login(user, pwd)
  File "/usr/local/lib/python3.4/dist-packages/skpy/conn.py", line 401, in login
    self.getRegToken()
  File "/usr/local/lib/python3.4/dist-packages/skpy/conn.py", line 518, in getRegToken
    headers=headers, json={"endpointFeatures": "Agent"})
  File "/usr/local/lib/python3.4/dist-packages/skpy/conn.py", line 202, in __call__
    resp = self.sess.request(method, url, headers=headers, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by OllieTerrance** [comment]
Are you sure you're using 2.11.1?  To check from Python: `import requests; print(requests.__version__)`

The latest version in the [Trusty repos](http://packages.ubuntu.com/trusty/python-requests) is only 2.2.1, which would cause this error as the `json` parameter is indeed not present back then.

I'm using 2.11.1 here and haven't come across this...

**Comment by firecurious** [comment]
You were right. Even though I had upgraded to 2.11.1, Python itself was apparently using an older version. I went through the Python 2.7, 3, and 3.4 folders and manually deleted everything related to Requests and then reinstalled 2.11.1 with pip, and now it works properly.

Thanks!
