### ISSUE TITLE
event.msg.chat throwing exception for non-group chats

### ISSUE THREAD

**Issue by Nothing4You** [OllieTerrance/SkPy#31]
Hey there,

I'm trying to write a small bot for some user interaction via skype.

```py
  def onEvent(self, event):

    if isinstance(event, SkypeNewMessageEvent) and not event.msg.userId == self.userId:
      text = event.msg.plain().strip()

      if text.startswith("!") and len(text) > 1:
        command = text[1:].split(" ")[0].lower()

        if command == "test":
          print(repr(event))
          print(repr(event.msg))
          print(repr(event.msg.chat))
```

When I send a message to the SkPy account in a group chat I can see the following:
```
SkypeNewMessageEvent(id=1064, type='NewMessage', time=datetime.datetime(2016, 11, 8, 13, 30, 2), msgId=<msgId>)
SkypeTextMsg(id='<msgId>', type='RichText', time=datetime.datetime(2016, 11, 8, 13, 30, 2, 855000), clientId='<clientId>', userId='live:<myUser>', chatId='19:<myGroupChat>@p2p.thread.skype', content='!test')
SkypeGroupChat(id='19:<myGroupChat>@p2p.thread.skype', topic='<topic>', creatorId='<creatorId>', userIds=['live:<myUser>', '<skpyUser>', 'and', 'some', 'others'], adminIds=['<others>'], open=False, history=False, picture='https://api.asm.skype.com/v1/objects/<whatever>/views/avatar_fullsize')
```

However, when I send a message directly it can't access the `chat` attribute on `event.msg`:
```
SkypeNewMessageEvent(id=1067, type='NewMessage', time=datetime.datetime(2016, 11, 8, 13, 30, 20), msgId=<msgId>)
SkypeTextMsg(id='<msgId>', type='Text', time=datetime.datetime(2016, 11, 8, 13, 30, 20, 433000), clientId='<clientId>', userId='live:<myUser>', content='!test')
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/skpy/chat.py", line 370, in __getitem__
    return super(SkypeChats, self).__getitem__(key)
  File "/usr/lib/python3.5/site-packages/skpy/core.py", line 138, in __getitem__
    return self.cache[key]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 78, in <module>
    main()
  File "./run.py", line 73, in main
    sk.loop()
  File "./run.py", line 49, in loop
    self.cycle()
  File "/usr/lib/python3.5/site-packages/skpy/main.py", line 205, in cycle
    self.onEvent(event)
  File "./run.py", line 38, in onEvent
    print(repr(event.msg.chat))
  File "/usr/lib/python3.5/site-packages/skpy/util.py", line 148, in chatObj
    return self.skype.chats[getattr(self, field)]
  File "/usr/lib/python3.5/site-packages/skpy/chat.py", line 372, in __getitem__
    return self.chat(key)
  File "/usr/lib/python3.5/site-packages/skpy/chat.py", line 408, in chat
    auth=SkypeConnection.Auth.RegToken, params={"view": "msnp24Equivalent"}).json()
  File "/usr/lib/python3.5/site-packages/skpy/conn.py", line 214, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from GET https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/None', <Response [400]>)
```
Am I supposed to check whether the message is coming from a group chat first?
If so, how would I do that? Checking whether the SkypeTextMsg has the `chatId` attribute?

**Comment by OllieTerrance** [comment]
`chatId` should be present regardless of whether it's a group or 1-to-1 chat...  🤔

What does `event.raw` look like?

**Comment by Nothing4You** [comment]
```
{
    'type': 'EventMessage',
    'id': 1020,
    'time': '2016-11-08T17:47:39Z',
    'resource': {
        'type': 'Message',
        'composetime': '2016-11-08T17:47:39.823Z',
        'content': '!test',
        'from': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:<my_userId>',
        'originalarrivaltime': '2016-11-08T17:47:39.823Z',
        'clientmessageid': '<clientId>',
        'ackrequired': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/<msgId>/ack',
        'imdisplayname': 'Richard Schwab',
        'conversationLink': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:<my_userId>',
        'messagetype': 'Text',
        'id': '<msgId>',
        'counterpartymessageid': '<counterpartymessageid>',
        'version': '<msgId>',
        'isactive': True
    },
    'resourceType': 'NewMessage',
    'resourceLink': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:<my_userId>/messages/<msgId>'
}```

**Comment by OllieTerrance** [comment]
Looks like I broke this in commit 9eb0914 by making the `@thread.skype` part required...

**Comment by Nothing4You** [comment]
Thank you.
Do you plan to release a new version soon? I'll add that change as a hotfix to my local version for now.

**Comment by OllieTerrance** [comment]
Looks like [we're probably due another release](https://github.com/OllieTerrance/SkPy/compare/v0.5.1...master)...  I'll rustle one up tonight.  😄
