### ISSUE TITLE
Couldn't retrieve Skype token from login response

### ISSUE THREAD

**Issue by zorar4ik** [OllieTerrance/SkPy#32]
Hi! I am novice in python, but I really liked you API, I used it successfuly in September-October, but now I am facing some issues when trying to run it, here's traceback: 
Traceback (most recent call last):
  File "zabbix-parsing.py", line 23, in <module>
    sk = Skype("my_login", "my_password") # connect to Skype
  File "/usr/local/lib/python2.7/dist-packages/skpy/main.py", line 70, in __init__
    self.conn.getSkypeToken()
  File "/usr/local/lib/python2.7/dist-packages/skpy/conn.py", line 259, in getSkypeToken
    self.login(user, pwd)
  File "/usr/local/lib/python2.7/dist-packages/skpy/conn.py", line 392, in login
    raise SkypeApiException("Couldn't retrieve Skype token from login response", loginResp)
skpy.core.SkypeApiException: ("Couldn't retrieve Skype token from login response", <Response [200]>)

Thanks in advance

**Comment by zorar4ik** [comment]
Seems like my bad, I panicked too early. Just updated skpy and seems like it's working. Sorry
