### ISSUE TITLE
Problem talking to a bot

### ISSUE THREAD

**Issue by adrianlzt** [OllieTerrance/SkPy#41]
I'm trying to talk to a bot but it raises an exception with a 404 http code:

```
>>> bot = sk.contacts.bots()[0]
>>> bot
SkypeBotUser(id='57bfbc6f-1556-46fc-b4fa-41ea57b26df6', name='Skyscanner', avatar='https://bot-framework.azureedge.net/bot-icons-v1/skyscanner_FvFDzr8uU6X5BNhm38qR3yTwCGsj1S191u7vbEF96nnaP.png', developer='Skysc
anner', trusted=True, locales=[], rating=0.0, description="The world's travel search engine", extra='<a href="https://www.skyscanner.net/termsofservice.aspx">Terms of Service</a><br/><a href="https://www.skyscan
ner.net/privacypolicy.aspx">Privacy Statement</a>', siteUrl='https://www.skyscanner.net', termsUrl='https://www.skyscanner.net/termsofservice.aspx', privacyUrl='https://www.skyscanner.net/privacypolicy.aspx')
>>> bot_chat = bot.chat
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    bot_chat = bot.chat
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/util.py", line 227, in wrapper
    cache[key] = fn(*args, **kwargs)
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/user.py", line 309, in chat
    return self.skype.chats["28:" + self.id]
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/chat.py", line 391, in __getitem__
    return self.chat(key)
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/chat.py", line 427, in chat
    auth=SkypeConnection.Auth.RegToken, params={"view": "msnp24Equivalent"}).json()
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/conn.py", line 215, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from GET https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:57bfbc6f-1556-46fc-b4fa-41ea57b26df6', <Response [404]>)
```

I have also problems trying to add a private bot:
```
>>> sk.contacts.bot("xxxxx4269-ac27-8c584ae6a29d")
SkypeContact(id='xxxxx-4269-ac27-8c584ae6a29d', name='xxxx', location=Location(), avatar='https://bot-framework.azureedge.net/bot-icons-v1/bot_DBMFdnxxxxxE3E193358Y4AYf1vEC6R2VP4Kr.png', aut
horised=True, blocked=False, favourite=True)
```

It returns a ``SkypeContact`` instead of a ``SkypeBotUser`` object.

With the id of the skyscanner bot it works well (creating the object, chat doesn't work neither):
```
>>> sk.contacts.bot("57bfbc6f-1556-46fc-b4fa-41ea57b26df6")
SkypeBotUser(id='57bfbc6f-1556-46fc-b4fa-41ea57b26df6', name='Skyscanner', avatar='https://bot-framework.azureedge.net/bot-icons-v1/skyscanner_FvFDzr8uU6X5BNhm38qR3yTwCGsj1S191u7vbEF96nnaP.png', developer='Skysc
anner', trusted=True, locales=[], rating=0.0, description="The world's travel search engine", extra='<a href="https://www.skyscanner.net/termsofservice.aspx">Terms of Service</a><br/><a href="https://www.skyscan
ner.net/privacypolicy.aspx">Privacy Statement</a>', siteUrl='https://www.skyscanner.net', termsUrl='https://www.skyscanner.net/termsofservice.aspx', privacyUrl='https://www.skyscanner.net/privacypolicy.aspx')
```

**Comment by OllieTerrance** [comment]
Looks like things have changed in the API...  😞

**Comment by OllieTerrance** [comment]
When you say a private bot, do you mean one you've built yourself and not one from the directory?  Plausible that the response is different.  Can you please repeat with `SKPY_DEBUG_HTTP=1` in your environment, and include the HTTP request for `sk.contacts.bot("xxxxx4269-ac27-8c584ae6a29d")` here.

Looks like we have to create a chat for bots ourselves.  I guess this doesn't affect regular contacts as the initial invite automatically creates the chat?

**Comment by adrianlzt** [comment]
With private bot I mean one not published.
I have tried now and it works. I have done the same:
```
 >>> sk.contacts.bot("xxxxx4269-ac27-8c584ae6a29d")
SkypeBotUser(id='xxxxx4269-ac27-8c584ae6a29d', name='xxxxxx', avatar='https://bot-framework.azureedge.net/bot-icons-v1/bot_DBMFdn3V
Z3SwGr452O9ZKxxxxxxxxxxEC6R2VP4Kr.png', developer='xxxx', trusted=False, locales=[], rating=0.0, description='xxxxx', ext
ra='<a href="http://example.com/">Terms of Service</a><br/><a href="http://example.com/">Privacy Statement</a>', termsUrl='http://example.co
m', privacyUrl='http://example.com')
```

mmm, I think that now it works because I'm logged also skype alpha for linux?


I have tried also with the Skyscanner bot.
Before adding to my contacts:
```
>>> sk.contacts.bot("57bfbc6f-1556-46fc-b4fa-41ea57b26df6").chat
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sk.contacts.bot("57bfbc6f-1556-46fc-b4fa-41ea57b26df6").chat
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/util.py", line 227, in wrapper
    cache[key] = fn(*args, **kwargs)
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/user.py", line 309, in chat
    return self.skype.chats["28:" + self.id]
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/chat.py", line 391, in __getitem__
    return self.chat(key)
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/chat.py", line 427, in chat
    auth=SkypeConnection.Auth.RegToken, params={"view": "msnp24Equivalent"}).json()
  File "/home/adrian/.virtualenvs/test/lib/python3.6/site-packages/skpy/conn.py", line 215, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from GET https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:57bfbc6f-1
556-46fc-b4fa-41ea57b26df6', <Response [404]>)
```

After adding the bot to my contacts in skype alpha:
```
>>> x= sk.contacts.bot("57bfbc6f-1556-46fc-b4fa-41ea57b26df6").chat
>>> x.sendMsg("hola")
SkypeTextMsg(type='Text', time=datetime.datetime(2017, 2, 1, 22, 37, 14, 427000), clientId='1485985030920', userId='adrianlzt', chatId='28:5
7bfbc6f-1556-46fc-b4fa-41ea57b26df6', content='hola')
```

Also comment that ``sendMsg`` send a strange message. At least it is shown strange in skype alpha and skype web:
![captura de pantalla de 2017-02-01 22-39-53](https://cloud.githubusercontent.com/assets/3237784/22527394/63f64f74-e8cf-11e6-84d2-fb2e70eb491f.png)

**Comment by OllieTerrance** [comment]
Ok, so I believe you need to send an invite to your bot before you can talk to it, which should hopefully handle creating a conversation you can access via [`SkypeUser.chat`](https://skpy.t.allofti.me/api.html#skpy.user.SkypeUser.chat).  It's working for you now as you've already created the conversation, and afaict you can't delete them again.

I've updated [`SkypeUser.invite()`](https://skpy.t.allofti.me/api.html#skpy.user.SkypeUser.invite) to work with bots, as it previously assumed a normal contact...

**Comment by OllieTerrance** [comment]
As for the weird message format, looks like messages sent via Skype for Web now include `"imdisplayname": "<name>"` in the payload.

**Comment by adrianlzt** [comment]
working thanks!
