### ISSUE TITLE
When initialing the instance, I got this error.

### ISSUE THREAD

**Issue by haonit** [OllieTerrance/SkPy#50]
Traceback (most recent call last):
  File "C:\Users\hao\Desktop\lil_tool_py\skype\test.py", line 4, in <module>
    sk = Skype(username, password) # connect to Skype
  File "C:\Python27\lib\site-packages\skpy\main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 262, in getSkypeToken
    self.liveLogin(user, pwd)
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 361, in liveLogin
    self.getRegToken()
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 423, in getRegToken
    self.syncEndpoints()
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 433, in syncEndpoints
    params={"view": "expanded"}, auth=self.Auth.RegToken).json().get("endpointPresenceDocs", []):
  File "C:\Python27\lib\site-packages\skpy\conn.py", line 215, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
SkypeApiException: ('404 response from GET https://client-s.gateway.messenger.live.com/v1/users/ME/presenceDocs/messagingService', <Response [404]>)

**Comment by OllieTerrance** [comment]
Can't seem to reproduce here. Please set `SKPY_DEBUG_HTTP=1` in your environment, try signing in again, and include the response from Skype below (make sure to blank your password and tokens).

**Comment by haonit** [comment]
It just work fine today. thx a lot anyway
