### ISSUE TITLE
sk.contacts.contact always returns null (no auth)

### ISSUE THREAD

**Issue by mitchcapper** [OllieTerrance/SkPy#61]
Originally found in ocilo/skype-http/issues/20

Calling sk.contacts.contact for any user on your list returns the same null (no auth).  
It is line https://github.com/OllieTerrance/SkPy/blob/master/skpy/user.py#L401 that is being entered.

Will try to investigate with the web client and will post back once we figure out.

Tried using your trace function(SKPY_DEBUG_HTTP) but it bailed out when logging in:

```
Traceback (most recent call last):
  File "/SkPy/skpy/conn.py", line 211, in __call__
    print(pformat(resp.json()))
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/SkPy/skpy/main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "/SkPy/skpy/conn.py", line 264, in getSkypeToken
    self.liveLogin(user, pwd)
  File "/SkPy/skpy/conn.py", line 361, in liveLogin
    self.tokens["skype"], self.tokenExpiry["skype"] = SkypeLiveAuthProvider(self).auth(user, pwd)
  File "/SkPy/skpy/conn.py", line 534, in auth
    params = self.getParams()
  File "/SkPy/skpy/conn.py", line 541, in getParams
    params={"client_id": "578134", "redirect_uri": "https://web.skype.com"})
  File "/SkPy/skpy/conn.py", line 213, in __call__
    print(resp.text)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf4' in position 23535: ordinal not in range(128)
````

Using master from GitHub, a skype login (not MSA)

**Comment by OllieTerrance** [comment]
See discussion in ocilo/skype-http#20 -- `POST https://api.skype.com/users/batch/profiles` appears to work as a drop-in replacement for the underlying call in [`SkypeContacts.contact()`](https://skpy.t.allofti.me/api.html#skpy.user.SkypeContacts.contact) (it's designed to take multiple IDs, but works fine with just one, and Skype for Web does do this e.g. from search results).

**Comment by demurgos** [comment]
Thanks for your help to quickly resolve this 👍
