### ISSUE TITLE
Cannot Send Messages

### ISSUE THREAD

**Issue by DigDugHub** [OllieTerrance/SkPy#67]
It always returns this:
```Traceback (most recent call last):
  File "C:/Users/sherl/PycharmProjects/SpamBot/Script.py", line 26, in <module>
    Chat.sendMsg(message)
  File "C:\Users\sherl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\skpy\chat.py", line 142, in sendMsg
    imdisplayname="{0}".format(self.skype.user.name), **kwargs)
AttributeError: 'str' object has no attribute 'user'
['8:live:sherlock21703', '19:98405c0dd426416992551801edfc7969@thread.skype', '8:live:2767b13067fa8168']

Process finished with exit code 1
```

I have no idea what could be causing this, and would like help.

My Code:

```import praw
import skpy
from skpy import Skype

i = 0
sk = Skype("skypespambot101@gmail.com", "...", connect=True)

reddit = praw.Reddit(client_id='...',
                     client_secret="...",
                     password='...',
                     user_agent='windows:..:1.0 (by /u/NonPostingBot)',
                     username='NonPostingBot')

sub = reddit.subreddit('copypasta')

while True:
    i = 0
    post = sub.random()
    message = str(post.selftext)
    print(message)
    spamlist = sk.chats.recent()
    grouplist = list(spamlist.keys())
    print(grouplist)
    for item in grouplist:
        Chat = skpy.SkypeChat(grouplist[i])
        Chat.sendMsg(message)
        i += 1
```

**Comment by OllieTerrance** [comment]
> ```
> Chat = skpy.SkypeChat(grouplist[i])
> ```

You're creating an empty conversation object and assigning the `skype` parameter of the chat class to a string, which isn't going to work.

You need to obtain conversations through `sk.chats`, not create them yourself -- see [Basic usage](https://skpy.t.allofti.me/usage.html#using-conversations).

**Comment by DigDugHub** [comment]
Thanks, I changed

```
for item in grouplist:
        Chat = skpy.SkypeChat(grouplist[i])
        Chat.sendMsg(message)
        i += 1
```
Into
```
    for item in grouplist:
        sk.chats[grouplist[i]].sendMsg(content=message)
        i += 1
```
And it works perfectly.
