### ISSUE TITLE
Exception on missed calls

### ISSUE THREAD

**Issue by phiresky** [OllieTerrance/SkPy#83]
```
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    nxt = chat.getMsgs()
  File ".local/lib/python3.6/site-packages/skpy/chat.py", line 48, in getMsgs
    return [SkypeMsg.fromRaw(self.skype, json) for json in resp.get("messages", [])]
  File ".local/lib/python3.6/site-packages/skpy/chat.py", line 48, in <listcomp>
    return [SkypeMsg.fromRaw(self.skype, json) for json in resp.get("messages", [])]
  File ".local/lib/python3.6/site-packages/skpy/msg.py", line 251, in fromRaw
    return msgCls(skype, raw, **msgCls.rawToFields(raw))
  File ".local/lib/python3.6/site-packages/skpy/msg.py", line 654, in rawToFields
    fields.update({"state": {"started": cls.State.Started, "ended": cls.State.Ended}[listTag.get("type")],
KeyError: 'missed'
```

Api response looks like this instead of something with type=started / ended

```
 {'clientmessageid': '...',
               'composetime': '[isodate]',
               'content': '<partlist type="missed" alt="" '
                          'callId="[guid]"><part '
                          'identity="[id]"><name>a</name></part><part '
                          'identity="[id]"><name>b '
                          '</name></part></partlist>',
```

The exception happens in this line:

```
        fields.update({"state": {"started": cls.State.Started, "ended": cls.State.Ended}[listTag.get("type")],
```

**Comment by OllieTerrance** [comment]
Easy enough to add another state (and that should perhaps handle unknown states more gracefully).

Out of interest, what type of client is making the call, and in a group or a private chat?  Trying it here from the Windows client, a missed call seems to still yield an "ended" event on the SkPy end rather than "missed".

**Comment by phiresky** [comment]
I'm not sure, but I'm fairly sure it's either a call from web.skype.com or from the android app.
